workspace = { members = ["app"] }

[package]
name = "spic-scale"
version = "0.1.0"
edition = "2021"

[dependencies]
num-traits = "0.2.19"
rayon = { version = "1.10.0", optional = true }

[features]
default = []
rayon = ["dep:rayon"]